### ISSUE TITLE
Not working with Puppet 4 (or parser future) ?

### ISSUE THREAD

**Issue by Jeoffreybauvin** [rplessl/puppet-telegraf#15]
Hi,

It seems that this module is not working with Puppet 4 (or with parser future) : 

I have this code : 

```puppet
  class { '::telegraf':
    install_from_repository   => false,
    version                   => '0.2.4',
    outputs_influxdb_enabled  => true,
    outputs_influxdb_urls     => ['http://localhost:8086'],
    outputs_influxdb_database => 'telegraf',
    outputs_influxdb_username => $influxdb_telegraf_user,
    outputs_influxdb_password => $influxdb_password,
    agent_hostname            => $::fqdn,
  }
```

And Influxdb output is never enabled !

But, for example, with this :  

```puppet
class telegraf::config (
  $outputs_influxdb_enabled  = $telegraf::outputs_influxdb_enabled,
) {
```

It's working fine.

Regards,

**Comment by rplessl** [comment]
Hi @Jeoffreybauvin,

Thanks for reporting this issue. 

Could you test my branch https://github.com/rplessl/puppet-telegraf/tree/15-puppet4?

Myself, I am using puppet 3.8 at the moment in my / our own production environments.

**Comment by rplessl** [comment]
Merged branch 15-puppet4 to master today
