### ISSUE TITLE
make ready for telegraf 0.10.x

### ISSUE THREAD

**Issue by rplessl** [rplessl/puppet-telegraf#19]
make ready for telegraf 0.10.x

**Comment by ntent-ashton** [comment]
Hey what's the status on this?  Any work I can pick up and help finish?

**Comment by xiii** [comment]
Hey,
Wanted to use the module too.I found that today that might help(didn't test
it yet)

https://forge.puppetlabs.com/datacentred/telegraf/readme

Seems to be compatible with the latest config file changes that rpl's
module is missing.

Cheers

**Comment by ntent-ashton** [comment]
Thanks a lot, I'll check that out in the meantime.

**Comment by rplessl** [comment]
close this issue will merge telegraf ready parts in new issue
