### ISSUE TITLE
dpkg error on subsequent Puppet runs after telegraf is installed

### ISSUE THREAD

**Issue by yankcrime** [rplessl/puppet-telegraf#3]
dpkg errors on Puppet runs after telegraf is installed the first time when `install_from_repository` is set to false. 

This is because `dpkg` is still executed even though the package is installed due to the ordering and dependancies in the `telegaf::install` class for Debian derivatives;  `Exec['telegraf_wget']` is in the catalogue regardless of the status of the `unless` attribute for that resource, so `dpkg` is executed with a path to a file that's already been removed.

**Comment by rplessl** [comment]
Good Catch @yankcrime!
